### ISSUE TITLE
Clothing Stores

### ISSUE THREAD

**Issue by Pac-Man-PT** [Project-India/Pi-clothing#1]
In clothing stores, the character option appears. It shouldn't show up. Only show up for new player to configure they character.
Thanks...
![image](https://user-images.githubusercontent.com/108277657/178578438-e216ac28-c2a7-4dd7-9e99-9cc209e2387a.png)

**Comment by Pavan576** [comment]
we are looking into it thanks for letting know us!!

**Comment by kunaltak606** [comment]
bro its not an issue this script is made like this ask from qbcore | this is not an html error , we only give html support to our redesign resources!
